### ISSUE TITLE
Map not show any data

### ISSUE THREAD

**Issue by ckocank** [bsmithio/OPNsense-Dashboard#48] opened 2023-06-24 09:35 UTC
I got every up and running but the map. 
I tried to create a new license key and waited for more than 5 mins, using that key to download the new GeoLite2-Country.mmdb, edit execution order in Graylog, and enable all message processors. 
<img width="517" alt="image" src="https://github.com/bsmithio/OPNsense-Dashboard/assets/25784815/5f08f097-ce5e-4069-becf-131956dee837">

**Comment by bsmithio** [comment] 2023-06-26 23:47
Hello, the first thing I would try in Graylog is navigate to System -> Lookup Tables -> Data Adapters -> Google any country IP address and use it under "Test Lookup". Here is an [example](https://global.discourse-cdn.com/business6/uploads/graylog/original/2X/4/4f9978b4dbdb5288376f7141e915837d4966c9c3.png) of the output you should receive when making a test lookup.

**Comment by ckocank** [comment] 2023-06-27 05:11
![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/25784815/04279ca4-814a-4101-9881-57180f7e6420)

yes, I have the same output.

**Comment by ckocank** [comment] 2023-06-27 05:11
> Hello, the first thing I would try in Graylog is navigate to System -> Lookup Tables -> Data Adapters -> Google any country IP address and use it under "Test Lookup". Here is an [example](https://global.discourse-cdn.com/business6/uploads/graylog/original/2X/4/4f9978b4dbdb5288376f7141e915837d4966c9c3.png) of the output you should receive when making a test lookup.

![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/25784815/06939004-87ed-4214-98a7-ecdc5ce4494d)

yes, I have the same output.

**Comment by ckocank** [comment] 2023-06-27 07:39
![image](https://github.com/bsmithio/OPNsense-Dashboard/assets/25784815/e2731794-1907-4afb-a241-b0dac05598c8)

Today I check the dash board again
I don't know this is success or not

**Comment by bsmithio** [comment] 2023-10-10 20:08
I believe the issue is fixed now with all the recent updates I've pushed.

**Closed by bsmithio** 2023-10-10 20:08 UTC
